"""Add leave_type to TeacherLeave

Revision ID: 011a4fc2f66d
Revises: 13e16f5b1661
Create Date: 2026-07-25 12:26:41.314313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011a4fc2f66d'
down_revision: Union[str, Sequence[str], None] = '13e16f5b1661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_leaves', sa.Column('leave_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_leaves', 'leave_type')
    # ### end Alembic commands ###
