"""per_class_subject_code

Revision ID: 98e5afee936f
Revises: 011a4fc2f66d
Create Date: 2026-07-25 15:00:21.973389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e5afee936f'
down_revision: Union[str, Sequence[str], None] = '011a4fc2f66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_code'))
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=False)
        batch_op.create_unique_constraint('uq_subject_code_class', ['code', 'class_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subject_code_class', type_='unique')
        batch_op.drop_index(batch_op.f('ix_subjects_code'))
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=1)

    # ### end Alembic commands ###
